name: Verse of the Day to Discord

on:
  schedule:
    # 06:30 South Africa time (UTC+2 → 04:30 UTC)
    - cron: "30 4 * * *"
  workflow_dispatch:

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests beautifulsoup4

      - name: Send Verse of the Day to Discord
        env:
          DISCORD_WEBHOOK_URL: ${{ secrets.DISCORD_VOTD_WEBHOOK_URL }}
          DISCORD_WEBHOOK_URL_2: ${{ secrets.DISCORD_WEBHOOK_URL2 }}
        run: |
          python votd_to_discord.py
          export DISCORD_WEBHOOK_URL=$DISCORD_WEBHOOK_URL_2
          python votd_to_discord.py
